### ISSUE TITLE
Unable to load with latest version of Consecration

### ISSUE THREAD

**Issue by anIceyGirl** [Azmalent/cuneiform#2]
[crash-2021-05-12_13.54.49-fml.txt](https://github.com/Azmalent/cuneiform/files/6468201/crash-2021-05-12_13.54.49-fml.txt)
[Consecration Mod Page](https://www.curseforge.com/minecraft/mc-mods/consecration)

I'm pretty sure this is just a case of the way forge handles optional dependencies being changed, which I'm sure as you know broke a ton of mods.

**Comment by Sunconure11** [comment]
Can confirm the same issue. @Azmalent

**Comment by Azmalent** [comment]
Fixed in the new release. The tweaks were removed but I'll release them as a separate mod in the future.
